call phpunit block_formal_langs_c_language_test blocks/formal_langs/tests/test_c_language.php
call phpunit block_formal_langs_simple_english_language_test blocks/formal_langs/tests/test_simple_english_language.php
call phpunit block_formal_langs_token_base_is_same blocks/formal_langs/tests/test_is_same.php

call phpunit block_formal_langs_token_base_test blocks/formal_langs/tests/test_damerau_levenshtein.php
call phpunit block_formal_langs_token_base_test blocks/formal_langs/tests/test_possible_pair.php
call phpunit block_formal_langs_token_base_test blocks/formal_langs/tests/test_look_for_matches.php
call phpunit block_formal_langs_token_base_test blocks/formal_langs/tests/test_group_matches.php
call phpunit block_formal_langs_token_base_test blocks/formal_langs/tests/test_compare_groups.php
call phpunit block_formal_langs_token_base_test blocks/formal_langs/tests/test_redaction.php
call phpunit block_formal_langs_token_base_test blocks/formal_langs/tests/test_correct_mistakes.php

call phpunit block_formal_langs_token_base_test blocks/formal_langs/tests/test_group_matches_for_bypass.php
call phpunit block_formal_langs_token_base_test blocks/formal_langs/tests/test_look_for_matches_for_bypass.php

call phpunit block_formal_langs_token_base_test blocks/formal_langs/tests/test_compared_corrected.php