<?php
/**
 * Defines error classes for the correct writing question.
 *
 * Errors are teacher errors: e.g. lexical and syntax error in answers,
 * provided by the teacher to the question. All supplied answers must be
 * a valid text in given language!
 *
 * @copyright &copy; 2011  Oleg Sychev
 * @author Oleg Sychev, Volgograd State Technical University
 * @license http://www.gnu.org/copyleft/gpl.html GNU Public License
 * @package questions
 */

defined('MOODLE_INTERNAL') || die();

//Other necessary requires

//Base class for answer error
abstract class  qtype_correctwriting_answer_error {
    //Error position as qtype_correctwriting_node_position object
    public $position;
    //Language name
    public $languagename;
    //Error message, generated by constructor
    public $errormsg;
}
?>