<?php
// This file is part of CorrectWriting question type - https://code.google.com/p/oasychev-moodle-plugins/
//
// CorrectWriting question type is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// CorrectWriting is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with CorrectWriting.  If not, see <http://www.gnu.org/licenses/>.

/**
 * A token pair, which defines a mapping from tokens of enumcorrectstring, generated
 * by enum_analyzer to a correctstring
 *
 * @package    qtype
 * @subpackage correctwriting
 * @copyright  2011 Sychev Oleg
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
defined('MOODLE_INTERNAL') || die();

/**
 * @class qtype_correctwriting_enum_token_pair
 *
 * Defines a mapping from tokens of enumcorrectstring, generated by enum_analyzer
 * to a correctstring
 */
class qtype_correctwriting_enum_token_pair {
    /**
     * An index of token from enum processed string
     * @var int
     */
    public $enumcorrecttokenindex;
    /**
     * An index of token from correct string
     * @var int
     */
    public $correcttokenindex;

    /**
     * Constructs new token pair
     * @param int $enumcorrecttokenindex An index of token from enum processed string
     * @param int $correcttokenindex An index of token from correct string
     */
    public function __construct($enumcorrecttokenindex, $correcttokenindex) {
        $this->enumcorrecttokenindex = $enumcorrecttokenindex;
        $this->correcttokenindex = $correcttokenindex;
    }

}