call phpunit qtype_correctwriting_sequence_analyzer_test question/type/correctwriting/tests/test_sequence_analyzer.php
call phpunit qtype_correctwriting_sequence_analyzer_test question/type/correctwriting/tests/test_grade_response.php
