<?php
function xmldb_block_supervised_upgrade($oldversion = 0) {
    global $DB;
    $dbman = $DB->get_manager();

    $result = true;

    /// Add a new column duration to the classes
    if ($result && $oldversion < 2013091801) {
        // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.
		// Define field duration to be added to classes.
        $table = new xmldb_table('classes');
        $field = new xmldb_field('duration', XMLDB_TYPE_CHAR, '20', null, XMLDB_NOTNULL, null, null, 'timestart');
        // Conditionally launch add field duration.
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }
        // Supervised savepoint reached.
        upgrade_block_savepoint(true, 2013091801, 'supervised');
    }
    return $result;
}