<?php
//global $CFG;
//require_once($CFG->dirroot.'/course/moodleform_mod.php');
define('POASASSIGNMENT_GRADER_NO_TEST', 0);
define('POASASSIGNMENT_GRADER_COMMON_TEST', 1);
define('POASASSIGNMENT_GRADER_INDIVIDUAL_TEST', 2);

define('POASASSIGNMENT_GRADER_SHOW_TESTING_PROGRAM_FEEDBACK', 1);
define('POASASSIGNMENT_GRADER_SHOW_TEST_INPUT_DATA', 2);
define('POASASSIGNMENT_GRADER_SHOW_OUTPUT_STUDENT_DATA', 4);
define('POASASSIGNMENT_GRADER_SHOW_DIFF', 8);
define('POASASSIGNMENT_GRADER_SHOW_TESTS_NAMES', 16);
define('POASASSIGNMENT_GRADER_SHOW_NUMBER_OF_PASSED_TESTS', 32);
define('POASASSIGNMENT_GRADER_SHOW_RATING', 64);

/**
 * Saves data generated by testing program 
 */
class simple_test_result {
    /**
     * Test name
     */
    public $testname;
    /** 
     * Shows, was the test completed successfully
     */
    public $issuccessful;
    /**
     * Input data for the test
     */
    public $testinputdata;
    /**
     * Result data of student's submission
     */
    public $studentoutputdata;
    /**
     * Testing program comments for the test
     */
    public $feedback;
    /**
     * Difference between test output data and student's submission
     */
    public $outputdiff;
}

/* 
 * Parent of all graders classes
 */
abstract class grader {


    
    /**
     * Returns test mode of this grader (NO_TEST, COMMON_TEST or INDIVIDUAL_TEST)
     * @return int test mode
     */
    public function get_test_mode() {
        return POASASSIGNMENT_GRADER_NO_TEST;
    }
    
    /**
     * Returns name of the grader
     * @return string name of the grader
     */
    public function name() {
        return 'abstract grader';
    }
    
    /**
     * Checks poasassignment options to be sure this grader can be 
     * used
     * @param array $data poasassignment options
     * @param array $errors denied options
     */
    public static function validation($data, &$errors) {
    }
    
    public function test_attempt($attemptid, $taskid) {
    }
    
    // Заполняются после выполнения оценивания (массив simple_test_result'ов)
    private $testresults;
    private $successfultestscount;
    
    public function show_result($options) {
        //TODO: вернемся когда это можно будет увидеть, остальные флаги нужно доработать еще будет
        $html = "";
        if($options & POASASSIGNMENT_GRADER_SHOW_RATING) 
            $html += "<br>Rating : ".(100 * $successfultestscount / count($testresults));
        if($options & POASASSIGNMENT_GRADER_SHOW_NUMBER_OF_PASSED_TESTS)
            $html += "<br>Passed tests : ".$successfultestscount;
        
        foreach ($testresults as $testresult) {
            if($options & POASASSIGNMENT_GRADER_SHOW_TESTS_NAMES)
                $html += "<br>".$testresult->testname;
            if($options & POASASSIGNMENT_GRADER_SHOW_TEST_INPUT_DATA)
                $html += "<br>".$testresult->testinputdata;
        }
    }
    
    // TODO: работа с тестами когда ими займусь ближе
        
    // Редактирование тестов( Отвечает за добавление новых тестов и редактирование существующих)
    function edit_tests($tests) {
        return null;
    }
    // Отключает тест
    function turn_off_test($testid) {
        return null;
    }
    // Полностью удаляет тест
    function delete_test($testid) {
        return null;
    }
    
    // Экспорт тестов
    function tests_export($exportParams) {
        return null;
    }
    
    // Импорт тестов
    function tests_import($importParams) {
        return null;
    }
        
    // Производит оценку ответа $submission на задание $taskid конкретного poasassignment'a
    function evaluate($submission,$poasassignmentid,$taskid=-1) {
        return array();
    }
        
    // Отображает список тестов
    function show_tests($poasassignmentid,$taskid=-1){
    
    }
}